// <auto-generated />
using System;
using HMS_WebAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HMS_WebAPI.Migrations
{
    [DbContext(typeof(HMSContext))]
    partial class HMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("HMS_WebAPI.Models.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "reception"
                        },
                        new
                        {
                            Id = 3,
                            Name = "bar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "wellness"
                        },
                        new
                        {
                            Id = 5,
                            Name = "restorant"
                        },
                        new
                        {
                            Id = 6,
                            Name = "account"
                        });
                });

            modelBuilder.Entity("HMS_WebAPI.Models.SessionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAccess")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("HMS_WebAPI.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoginName")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobTitle = "rendszergazda",
                            LoginName = "admin",
                            Name = "administrator",
                            PasswordHash = "+mhDhHFuHeMET3Sd4pau/cn8HfZCS89yojUwSYuppKc="
                        },
                        new
                        {
                            Id = 2,
                            JobTitle = "igazgató",
                            LoginName = "csak.otto",
                            Name = "Csák Ottó",
                            PasswordHash = "H7rWMBHQm9qZKbHvhrOGwEAfw0XAj3kY3lzSLoI+uB8="
                        },
                        new
                        {
                            Id = 3,
                            JobTitle = "recepciós",
                            LoginName = "varadi.nikoletta",
                            Name = "Váradi Nikoletta",
                            PasswordHash = "zQ26Ku+e1ZurG7XAyzgcEEvvkl07ZTdvFar2Uq8tcOU="
                        },
                        new
                        {
                            Id = 4,
                            JobTitle = "bármixer",
                            LoginName = "farkas.vilmos",
                            Name = "Farkas Vilmos",
                            PasswordHash = "erbR1BTveAC4DFaISzhJCJd+wA0aQUlbW46hlQ/1UYo="
                        },
                        new
                        {
                            Id = 5,
                            JobTitle = "pincér",
                            LoginName = "pinter.bea",
                            Name = "Pintér Bea",
                            PasswordHash = "yWzSCV3ynrhDCR7lzM4G/mZWLBRhtNqtA4Z6iTfwkQk="
                        });
                });

            modelBuilder.Entity("HMS_WebAPI.Models.UserRoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("userroles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 5,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("HMS_WebAPI.Models.SessionModel", b =>
                {
                    b.HasOne("HMS_WebAPI.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HMS_WebAPI.Models.UserRoleModel", b =>
                {
                    b.HasOne("HMS_WebAPI.Models.RoleModel", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HMS_WebAPI.Models.UserModel", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HMS_WebAPI.Models.RoleModel", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HMS_WebAPI.Models.UserModel", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
